#pragma once
#include "lvgl.h"

// Generated by tools/02_theme.py — every colour sits exactly on the RGB565
// grid, so what you read here is what the ST77922 displays. Changing a red or
// blue channel by less than 8 (or green by less than 4) changes nothing.
//
// Minimum pairwise separation after quantisation is 22.6 in both palettes,
// checked with a dark-adaptation weighting. The first pass failed this:
// Surface2 and RuleFaint collapsed to the identical 565 code.

typedef struct {
  lv_color_t ground, surface, surface2, rule, ruleFaint;
  lv_color_t textHi, textMid, textLow;
  lv_color_t accent, accentDim, warn, alert;
} onstep_palette_t;

extern const onstep_palette_t onstep_day;
extern const onstep_palette_t onstep_night;

// Night mode is a palette swap on the same layout, not a second design.
extern const onstep_palette_t *onstep_pal;
void onstep_set_night(bool on);
