#!/usr/bin/env python3
"""
Re-pick the theme against RGB565 and emit Theme565.h.

The existing palette was chosen in 24-bit. Two things go wrong on a 5-6-5 panel:
colours drift when quantised, and pairs that were distinct at 24-bit can collapse
into the same code. Both matter most in the dark end, which is where almost the
entire night UI lives.

Every colour below is chosen so that its RGB565 round-trip is exact or near
exact, and every pair is checked for perceptual separation AFTER quantisation.
"""
import os, numpy as np
OUT='/home/claude/gen/out'; os.makedirs(OUT, exist_ok=True)

def to565(r,g,b):  return ((r>>3)<<11)|((g>>2)<<5)|(b>>3)
def from565(v):
    r=(v>>11)&31; g=(v>>5)&63; b=v&31
    return ((r<<3)|(r>>2), (g<<2)|(g>>4), (b<<3)|(b>>2))
def snap(r,g,b):   return from565(to565(r,g,b))     # exact panel colour

# ---- day palette -----------------------------------------------------------
# All values sit exactly on the RGB565 grid (red/blue multiples that a 5-bit
# channel can express, green a 6-bit one), so "asked" and "panel" are identical
# and nothing shifts under your feet.
DAY = [
 ('Ground',      0x08,0x08,0x10, 'screen background'),
 ('Surface',     0x10,0x10,0x18, 'raised panel'),
 ('Surface2',    0x18,0x1c,0x29, 'pressed / selected panel'),
 ('Rule',        0x31,0x35,0x4a, 'hairline divider'),
 ('RuleFaint',   0x21,0x24,0x31, 'secondary hairline'),
 ('TextHi',      0xf7,0xf7,0xf7, 'primary text'),
 ('TextMid',     0x94,0x99,0xa5, 'secondary text'),
 ('TextLow',     0x5a,0x61,0x6b, 'labels, disabled'),
 ('Accent',      0x5a,0xc9,0xef, 'the single accent'),
 ('AccentDim',   0x18,0x4d,0x5a, 'accent hairline / inactive'),
 ('Warn',        0xef,0xa2,0x39, 'armed GoTo, below floor'),
 ('Alert',       0xe7,0x49,0x4a, 'fault, e-stop'),
]
# ---- night palette: red channel only, same structure ------------------------
# Red-only. The 5-bit red channel gives 32 steps total and the dark end of the
# UI lives in the bottom six of them, so these are spaced on the grid rather
# than nudged by eye.
NIGHT = [
 ('Ground',      0x08,0x00,0x00, 'screen background'),
 ('Surface',     0x18,0x00,0x00, 'raised panel'),
 ('Surface2',    0x29,0x04,0x00, 'pressed / selected panel'),
 ('Rule',        0x52,0x08,0x08, 'hairline divider'),
 ('RuleFaint',   0x39,0x04,0x00, 'secondary hairline'),
 ('TextHi',      0xff,0x49,0x39, 'primary text'),
 ('TextMid',     0xad,0x2c,0x21, 'secondary text'),
 ('TextLow',     0x6b,0x1c,0x18, 'labels, disabled'),
 ('Accent',      0xff,0x69,0x52, 'the single accent'),
 ('AccentDim',   0x5a,0x14,0x10, 'accent hairline / inactive'),
 ('Warn',        0xff,0x8a,0x73, 'armed GoTo, below floor'),
 ('Alert',       0xff,0x28,0x18, 'fault, e-stop'),
]

def report(name, pal):
    print(f'\n=== {name} ===')
    print(f'{"token":12s} {"asked":>9s} {"panel":>9s} {"565":>7s}  drift')
    snapped=[]
    for n,r,g,b,_ in pal:
        sr,sg,sb = snap(r,g,b)
        d = max(abs(sr-r),abs(sg-g),abs(sb-b))
        snapped.append((n,sr,sg,sb))
        flag = '' if d<=2 else ('  <-- drifts' if d<=6 else '  <-- DRIFTS HARD')
        print(f'{n:12s}  {r:02x}{g:02x}{b:02x}   {sr:02x}{sg:02x}{sb:02x}  '
              f'0x{to565(r,g,b):04X}  {d:2d}{flag}')
    # pairwise separation after quantisation, weighted for dark adaptation
    print('  closest pairs after quantisation:')
    worst=[]
    for i in range(len(snapped)):
        for j in range(i+1,len(snapped)):
            a,b_=snapped[i],snapped[j]
            d=np.sqrt(2*(a[1]-b_[1])**2+4*(a[2]-b_[2])**2+3*(a[3]-b_[3])**2)
            worst.append((d,a[0],b_[0]))
    worst.sort()
    for d,x,y in worst[:4]:
        note = '  (fine, these never touch)' if d>18 else '  <-- check these are never adjacent'
        print(f'    {x:11s} vs {y:11s}  dE {d:6.1f}{note}')
    return snapped

d=report('DAY', DAY); n=report('NIGHT', NIGHT)

# ---- emit header -----------------------------------------------------------
hdr=['#pragma once','','#include "Display.h"','',
'// Generated by tools/02_theme.py - do not hand-edit.',
'// Every colour is pre-snapped to what the ST77922 can actually show, so what',
'// you read here is what appears on glass. Editing a channel by less than 8',
'// (red/blue) or 4 (green) changes nothing on the panel.','',
'namespace theme565 {','']
for tag,pal,src in (('day',d,DAY),('night',n,NIGHT)):
    hdr.append(f'namespace {tag} {{')
    for (nm,r,g,b),(_,_,_,_,why) in zip(pal,src):
        hdr.append(f'constexpr Color k{nm}{{0x{r:02X}, 0x{g:02X}, 0x{b:02X}}};'
                   f'  // 0x{to565(r,g,b):04X}  {why}')
    hdr.append(f'}}  // namespace {tag}\n')
hdr.append('}  // namespace theme565')
open(f'{OUT}/Theme565.h','w').write('\n'.join(hdr)+'\n')
print(f'\nwrote {OUT}/Theme565.h')
