#!/usr/bin/env python3
"""
Convert the 4-bit alpha icon/glyph sheets into LVGL image descriptors.

LV_IMG_CF_ALPHA_4BIT is exactly our storage format already: two 4-bit alpha
samples per byte, high nibble = left pixel, row-major. So this is a relabelling
rather than a conversion — no resampling, no quality loss. LVGL tints them with
the style's img_recolor at draw time, which is what lets one asset serve both
the day and night palettes.
"""
import os
OUT='lvgl_out/assets'; os.makedirs(OUT,exist_ok=True)

ICONS=['gal_spiral','gal_barred','gal_elliptical','gal_lenticular','gal_irregular',
 'gal_interacting','gal_cluster','neb_emission','neb_reflection','neb_dark',
 'neb_planetary','neb_supernova','neb_hii','neb_bright','cl_open','cl_globular',
 'cl_open_neb','asterism','star_double','star_multiple','star_variable',
 'quasar','unknown']
GLYPHS=['info','center','goto','image','notes','back','align','guide','tools',
 'wifi0','wifi1','wifi2','wifi3','link','tracking','battery','sdcard','warning',
 'park','filter','sort','moon','clock','check','close','chev_left','chev_right',
 'chev_up','chev_down','stick','dpad','btn_a','btn_b','btn_x','btn_y']

def emit(src, names, size, prefix, outfile):
    per = size*((size+1)//2)
    data = open(src,'rb').read()
    lines = ['#include "lvgl.h"','',
        f'// Generated by tools/13_lvgl_assets.py — {len(names)} x {size}px,',
        '// LV_IMG_CF_ALPHA_4BIT. Tint with lv_obj_set_style_img_recolor().','']
    for i,n in enumerate(names):
        blob = data[i*per:(i+1)*per]
        sym = f'{prefix}_{n}_{size}'
        # Wrap between complete byte tokens. Splitting the rendered text at an
        # arbitrary character count can turn `0x00` into `0` + `x00` on the
        # next line, producing invalid C source.
        tokens = [f'0x{b:02x}' for b in blob]
        wrapped='\n'.join('  '+','.join(tokens[j:j+16])+','
                          for j in range(0, len(tokens), 16))
        lines += [f'static const uint8_t {sym}_map[] = {{',wrapped,'};','',
          f'const lv_img_dsc_t {sym} = {{',
          '  .header.cf = LV_IMG_CF_ALPHA_4BIT,',
          '  .header.always_zero = 0,',
          f'  .header.w = {size},',
          f'  .header.h = {size},',
          f'  .data_size = {len(blob)},',
          f'  .data = {sym}_map,',
          '};','']
    open(f'{OUT}/{outfile}.c','w').write('\n'.join(lines)+'\n')
    # header
    h = ['#pragma once','#include "lvgl.h"','']
    for n in names: h.append(f'extern const lv_img_dsc_t {prefix}_{n}_{size};')
    h += ['', f'#define {prefix.upper()}_COUNT {len(names)}','',
          f'// Index-addressable table, so a catalog row can do',
          f'//   lv_img_set_src(img, {prefix}_table_{size}[obj.type]);',
          f'extern const lv_img_dsc_t* const {prefix}_table_{size}[{len(names)}];']
    open(f'{OUT}/{outfile}.h','w').write('\n'.join(h)+'\n')
    # table
    with open(f'{OUT}/{outfile}.c','a') as f:
        f.write(f'\nconst lv_img_dsc_t* const {prefix}_table_{size}[{len(names)}] = {{\n')
        for n in names: f.write(f'  &{prefix}_{n}_{size},\n')
        f.write('};\n')
    return os.path.getsize(f'{OUT}/{outfile}.c')

tot=0
for size,src,names,pref,out in [
   (24,'out/icons/dso_24.bin',ICONS,'dso','dso_icons_24'),
   (48,'out/icons/dso_48.bin',ICONS,'dso','dso_icons_48'),
   (16,'out/glyphs/glyphs_16.bin',GLYPHS,'ui','ui_glyphs_16'),
   (24,'out/glyphs/glyphs_24.bin',GLYPHS,'ui','ui_glyphs_24')]:
    n=emit(src,names,size,pref,out); tot+=n
    raw=len(names)*size*((size+1)//2)
    print(f'{out:16s} {len(names):3d} x {size:2d}px   {raw:6,d} B flash   ({n/1024:.0f} KB source)')
print(f'\ntotal flash for all icon + glyph assets: '
      f'{(23*288+23*1152+35*128+35*288)/1024:.1f} KB')
