#!/usr/bin/env python3
"""png2c.py - PNG -> UiAssets.cpp/.h, LV_IMG_CF_TRUE_COLOR_ALPHA (RGB565LE+A),
portable brace initializers (fixes '.header.cf' error on ESP32 core 3.x g++)."""
from PIL import Image
import os
SRC = "assets/screen_png"
import glob
names = sorted(os.path.splitext(os.path.basename(p))[0] for p in glob.glob(f"{SRC}/*.png"))
cpp = ['// Auto-generated by tools/png2c.py -- DO NOT EDIT BY HAND.',
       '// Regenerate: python3 tools/gen_assets.py && python3 tools/png2c.py',
       '#include "UiAssets.h"', '']
h   = ['#pragma once', '#define LV_CONF_INCLUDE_SIMPLE', '#include <lvgl.h>', '']
for n in names:
    img = Image.open(f"{SRC}/{n}.png").convert("RGBA")
    w, hh = img.size
    data = bytearray()
    for y in range(hh):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            data += bytes([v & 0xFF, v >> 8, a])
    arr = ", ".join(str(b) for b in data)
    cpp.append(f"static const uint8_t ui_img_{n}_map[] = {{ {arr} }};")
    cpp.append(f"const lv_img_dsc_t ui_img_{n} = {{")
    cpp.append(f"  .header = {{ .cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {hh} }},")
    cpp.append(f"  .data_size = {len(data)}, .data = ui_img_{n}_map")
    cpp.append("};"); cpp.append("")
    h.append(f"extern const lv_img_dsc_t ui_img_{n};")
open("UiAssets.cpp","w").write("\n".join(cpp))
open("UiAssets.h","w").write("\n".join(h) + "\n")
print("UiAssets.cpp:", os.path.getsize("UiAssets.cpp")//1024, "KB")
